"""
pushshiftDFSetupSA.py

This program modifies the dataframe generated by pushshift.py for the purposes 
of performing a sentiment analysis using libraries such as TextBlob, VADER, 
and NRC Lexicon.

Author: Joseph A. Tomasello 
"""


"""
BEGIN - SCRIPT PREPARATION
"""
import pandas as pd
import re
from vaderSA import *
"""
END - SCRIPT PREPARATION 
"""


"""
BEGIN - FUNCTIONS
"""

dataframe = pd.read_csv('dataset_all_posts_4years_SA.csv', encoding="utf8")

#vader_sentiment = dataframe.vader_sentiment

#print(vader_sentiment.head(3))
plot_title = 'VADER - Full Dataset\nKeyword-Based Sentiment Post Counts'
kw_list = ['mental health', 'depression', 'anxiety', 'suicide', 'time', 'life', 'family', 'help', 'friend']
instance_count = 1


vader_chart_multiple_bars_kw(plot_title, dataframe, kw_list, instance_count)

"""
END - FUNCTIONS
"""
